# Generated by Django 5.0.6 on 2024-07-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='reevaluationrequest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='reevaluationrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='ReEvaluationRequest',
        ),
    ]
