# Generated by Django 5.0.6 on 2024-07-27 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='answer_papers/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('subject1', models.IntegerField()),
                ('subject2', models.IntegerField()),
                ('subject3', models.IntegerField()),
                ('subject4', models.IntegerField()),
                ('subject5', models.IntegerField()),
                ('subject6', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RevaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.answerpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.studentmark')),
            ],
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherapp.studentmark'),
        ),
    ]
